id: I2D9933D4
default_language: mon
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:52:10.221425
last_modified: 2023-02-09 14:52:10.221550
source_metadata:
  title: 'PP: Vajracchedikā Prajñāpāramitā'
  language: mon
bases:
  8BD3:
    base_file: 8BD3.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
